export const VENDOR_COLORS: Record<string, string> = {
  "Bambu Lab|Alpine Green Sparkle": "3F5443",
  "Bambu Lab|Azure": "489FDF",
  "Bambu Lab|Bambu Green": "00AE42",
  "Bambu Lab|Beige": "DFD1A7",
  "Bambu Lab|Black Walnut": "4F3F24",
  "Bambu Lab|Black": "000000",
  "Bambu Lab|Blue Gray": "688197",
  "Bambu Lab|Blue": "0A2CA5",
  "Bambu Lab|Brick Red": "9F332A",
  "Bambu Lab|Bright Green": "BECF00",
  "Bambu Lab|Bronze": "847D48",
  "Bambu Lab|Brown Galaxy": "684A43",
  "Bambu Lab|Brown": "5B492F",
  "Bambu Lab|Burgundy Red": "951E23",
  "Bambu Lab|Classic Birch": "918669",
  "Bambu Lab|Classic Gold Sparkle": "CEA629",
  "Bambu Lab|Clay Brown": "995F11",
  "Bambu Lab|Clear Black": "5A5161",
  "Bambu Lab|Clear": "FFFFFF",
  "Bambu Lab|Cobalt Blue Metallic": "39699E",
  "Bambu Lab|Cobalt Blue": "0056B8",
  "Bambu Lab|Cocoa Brown": "6F5034",
  "Bambu Lab|Copper Brown Metallic": "AA6443",
  "Bambu Lab|Crimson Red Sparkle": "792B36",
  "Bambu Lab|Cyan": "0086D6",
  "Bambu Lab|Dark Gray": "545454",
  "Bambu Lab|FR Black": "000000",
  "Bambu Lab|FR Grey": "A8A8AA",
  "Bambu Lab|FR White": "FFFFFF",
  "Bambu Lab|For AMS Black": "000000",
  "Bambu Lab|For AMS Blue": "5898DD",
  "Bambu Lab|For AMS Gray": "939393",
  "Bambu Lab|For AMS Neon Green": "90FF1A",
  "Bambu Lab|For AMS Red": "ED0000",
  "Bambu Lab|For AMS White": "FFFFFF",
  "Bambu Lab|For AMS Yellow": "F9EF41",
  "Bambu Lab|Glow Blue": "7AC0E9",
  "Bambu Lab|Glow Green": "A1FFAC",
  "Bambu Lab|Glow Orange": "FF9D5B",
  "Bambu Lab|Glow Pink": "F17B8F",
  "Bambu Lab|Glow Yellow": "F8FF80",
  "Bambu Lab|Gold": "B28B33",
  "Bambu Lab|Gray": "C6C6C6",
  "Bambu Lab|Green Galaxy": "3B665E",
  "Bambu Lab|Green": "61BF36",
  "Bambu Lab|HF Black": "000000",
  "Bambu Lab|HF Blue": "002E96",
  "Bambu Lab|HF Cream": "F9DFB9",
  "Bambu Lab|HF Dark Gray": "515151",
  "Bambu Lab|HF Forest Green": "39541A",
  "Bambu Lab|HF Gray": "ADB1B2",
  "Bambu Lab|HF Green": "00AE42",
  "Bambu Lab|HF Lake Blue": "1F79E5",
  "Bambu Lab|HF Lime Green": "6EE53C",
  "Bambu Lab|HF Orange": "F75403",
  "Bambu Lab|HF Peanut Brown": "875718",
  "Bambu Lab|HF Red": "EB3A3A",
  "Bambu Lab|HF White": "FFFFFF",
  "Bambu Lab|HF Yellow": "FFD00B",
  "Bambu Lab|Hot Pink": "F5547C",
  "Bambu Lab|Indigo Purple": "482960",
  "Bambu Lab|Indigue Blue": "324585",
  "Bambu Lab|Iridium Gold Metallic": "B39B84",
  "Bambu Lab|Iris Purple": "69398E",
  "Bambu Lab|Iron Gray Metallic": "43403D",
  "Bambu Lab|Jade White": "FFFFFF",
  "Bambu Lab|Jeans Blue": "6E88BC",
  "Bambu Lab|Lake Blue": "0069B1",
  "Bambu Lab|Lava Gray": "4D5054",
  "Bambu Lab|Lavender": "7248BD",
  "Bambu Lab|Light Cyan": "C3E2D6",
  "Bambu Lab|Light Gray": "D1D3D5",
  "Bambu Lab|Lime Green": "7CD82B",
  "Bambu Lab|Lime": "C5ED48",
  "Bambu Lab|Magenta": "EC008C",
  "Bambu Lab|Malachite Green": "16B08E",
  "Bambu Lab|Maroon Red": "9D2235",
  "Bambu Lab|Matcha Green": "5C9748",
  "Bambu Lab|Matte Apple Green": "C2E189",
  "Bambu Lab|Matte Ash Gray": "9B9EA0",
  "Bambu Lab|Matte Bone White": "CBC6B8",
  "Bambu Lab|Matte Caramel": "AE835B",
  "Bambu Lab|Matte Charcoal": "000000",
  "Bambu Lab|Matte Dark Blue": "042F56",
  "Bambu Lab|Matte Dark Brown": "7D6556",
  "Bambu Lab|Matte Dark Chocolate": "4D3324",
  "Bambu Lab|Matte Dark Green": "68724D",
  "Bambu Lab|Matte Dark Red": "BB3D43",
  "Bambu Lab|Matte Desert Tan": "E8DBB7",
  "Bambu Lab|Matte Grass Green": "61C680",
  "Bambu Lab|Matte Ice Blue": "A3D8E1",
  "Bambu Lab|Matte Ivory White": "FFFFFF",
  "Bambu Lab|Matte Latte Brown": "D3B7A7",
  "Bambu Lab|Matte Lemon Yellow": "F7D959",
  "Bambu Lab|Matte Lilac Purple": "AE96D4",
  "Bambu Lab|Matte Mandarin Orange": "F99963",
  "Bambu Lab|Matte Marine Blue": "0078BF",
  "Bambu Lab|Matte Nardo Gray": "757575",
  "Bambu Lab|Matte Plum": "950051",
  "Bambu Lab|Matte Sakura Pink": "E8AFCF",
  "Bambu Lab|Matte Scarlet Red": "DE4343",
  "Bambu Lab|Matte Sky Blue": "56B7E6",
  "Bambu Lab|Matte Terracotta": "B15533",
  "Bambu Lab|Mint": "7AE1BF",
  "Bambu Lab|Mistletoe Green": "3F8E43",
  "Bambu Lab|Nature": "F9F7F2",
  "Bambu Lab|Navy Blue": "0C2340",
  "Bambu Lab|Nebulae Galaxy": "424379",
  "Bambu Lab|Neon Orange": "F68B1B",
  "Bambu Lab|Ochre Yellow": "C98935",
  "Bambu Lab|Olive": "789D4A",
  "Bambu Lab|Onyx Black Sparkle": "2D2B28",
  "Bambu Lab|Orange": "FF6A13",
  "Bambu Lab|Oxide Green Metallic": "1D7C6A",
  "Bambu Lab|Pink": "F55A74",
  "Bambu Lab|Pumpkin Orange": "FF9016",
  "Bambu Lab|Purple Galaxy": "594177",
  "Bambu Lab|Purple": "AF1685",
  "Bambu Lab|Red Granite": "AD4E38",
  "Bambu Lab|Red": "D32941",
  "Bambu Lab|Rosewood": "4C241C",
  "Bambu Lab|Royal Blue": "2842AD",
  "Bambu Lab|Royal Purple Sparkle": "483D8B",
  "Bambu Lab|Silk Blue": "147BD1",
  "Bambu Lab|Silk Copper": "5E4B3C",
  "Bambu Lab|Silk Gold": "E5B03D",
  "Bambu Lab|Silk Green": "4CE4A0",
  "Bambu Lab|Silk Pink": "EEB1C1",
  "Bambu Lab|Silk Purple": "854CE4",
  "Bambu Lab|Silk Silver": "EAECEB",
  "Bambu Lab|Silk White": "FFFFFF",
  "Bambu Lab|Silk+ Baby Blue": "A8C6EE",
  "Bambu Lab|Silk+ Blue": "008BDA",
  "Bambu Lab|Silk+ Candy Green": "018814",
  "Bambu Lab|Silk+ Candy Red": "D02727",
  "Bambu Lab|Silk+ Champagne": "F3CFB2",
  "Bambu Lab|Silk+ Gold": "F4A925",
  "Bambu Lab|Silk+ Mint": "96DCB9",
  "Bambu Lab|Silk+ Pink": "F7ADA6",
  "Bambu Lab|Silk+ Purple": "8671CB",
  "Bambu Lab|Silk+ Rose Gold": "BA9594",
  "Bambu Lab|Silk+ Silver": "C8C8C8",
  "Bambu Lab|Silk+ Titan Gray": "5F6367",
  "Bambu Lab|Silk+ White": "FFFFFF",
  "Bambu Lab|Silver": "87909A",
  "Bambu Lab|Slate Gray Sparkle": "8E9089",
  "Bambu Lab|Sunflower Yellow": "FEC600",
  "Bambu Lab|Support for ABS": "FFFFFF",
  "Bambu Lab|Support for PA/PET": "BECF00",
  "Bambu Lab|Support for PLA White": "FFFFFF",
  "Bambu Lab|Support for PLA/PETG Black": "000000",
  "Bambu Lab|Support for PLA/PETG Nature": "FFFFFF",
  "Bambu Lab|Tangerine Yellow": "FFC72C",
  "Bambu Lab|Titan Gray": "565656",
  "Bambu Lab|Tough+ Black": "000000",
  "Bambu Lab|Tough+ Cyan": "009BD8",
  "Bambu Lab|Tough+ Gray": "AFB1AE",
  "Bambu Lab|Tough+ Orange": "DC3A27",
  "Bambu Lab|Tough+ Silver": "959698",
  "Bambu Lab|Tough+ White": "FFFFFF",
  "Bambu Lab|Tough+ Yellow": "F4D53F",
  "Bambu Lab|Translucent Blue": "0047BB",
  "Bambu Lab|Translucent Brown": "C9A381",
  "Bambu Lab|Translucent Cherry Pink": "F5B6CD",
  "Bambu Lab|Translucent Gray": "8E8E8E",
  "Bambu Lab|Translucent Ice Blue": "B8CDE9",
  "Bambu Lab|Translucent Lavender": "B8ACD6",
  "Bambu Lab|Translucent Light Blue": "61B0FF",
  "Bambu Lab|Translucent Light Jade": "96D8AF",
  "Bambu Lab|Translucent Mellow Yellow": "F5DBAB",
  "Bambu Lab|Translucent Olive": "748C45",
  "Bambu Lab|Translucent Orange": "FF911A",
  "Bambu Lab|Translucent Pink": "F9C1BD",
  "Bambu Lab|Translucent Purple": "D6ABFF",
  "Bambu Lab|Translucent Red": "B50011",
  "Bambu Lab|Translucent Teal": "77EDD7",
  "Bambu Lab|Transparent": "FFFFFF",
  "Bambu Lab|Turquoise": "00B1B7",
  "Bambu Lab|Violet Purple": "583061",
  "Bambu Lab|White Aero": "F5F1DD",
  "Bambu Lab|White Marble": "F7F3F0",
  "Bambu Lab|White Oak": "D6CCA3",
  "Bambu Lab|White": "FFFFFF",
  "Bambu Lab|Yellow": "FCE900",
  "Extrudr|Anthracite": "293133",
  "Extrudr|Arctic White": "F4F4F4",
  "Extrudr|Basic - Black ": "1E1E1E",
  "Extrudr|Basic - CMYK Lithocyan": "84C3BE",
  "Extrudr|Basic - CMYK Lithomagenta": "CF3476",
  "Extrudr|Basic - CMYK Lithowhite": "F4F4F4",
  "Extrudr|Basic - CMYK Lithoyellow": "FFFF00",
  "Extrudr|Basic - Gold": "705335",
  "Extrudr|Basic - Transparent ": "FFFFFF",
  "Extrudr|Basic - White": "F4F4F4",
  "Extrudr|Black ": "1E1E1E",
  "Extrudr|Black": "1E1E1E",
  "Extrudr|Blue Fire": "102C54",
  "Extrudr|Bronze": "F80000",
  "Extrudr|Cherry Red": "D53032",
  "Extrudr|Copper": "8E402A",
  "Extrudr|Dark Wood": "59351F",
  "Extrudr|DuraPro - Anthracite": "293133",
  "Extrudr|DuraPro - Black ": "1E1E1E",
  "Extrudr|DuraPro - Black": "1E1E1E",
  "Extrudr|DuraPro - Blue": "1D1E33",
  "Extrudr|DuraPro - Dark Silver": "D0D0D0",
  "Extrudr|DuraPro - Emerald Green": "287233",
  "Extrudr|DuraPro - Grey": "CAC4B0",
  "Extrudr|DuraPro - Metallic": "828282",
  "Extrudr|DuraPro - Nature": "EAE6CA",
  "Extrudr|DuraPro - Neon Green": "00BB2D",
  "Extrudr|DuraPro - Neon Orange": "FF2301",
  "Extrudr|DuraPro - Neon Yellow": "FFFF00",
  "Extrudr|DuraPro - Orange": "F54021",
  "Extrudr|DuraPro - Red": "A52019",
  "Extrudr|DuraPro - Silver": "A5A5A5",
  "Extrudr|DuraPro - White": "F4F4F4",
  "Extrudr|DuraPro - Yellow": "FAD201",
  "Extrudr|Emerald Green": "287233",
  "Extrudr|Epic Purple": "4A192C",
  "Extrudr|FLEX - Anthracite - Medium": "293133",
  "Extrudr|FLEX - Black - Hard": "1E1E1E",
  "Extrudr|FLEX - Black - Medium": "1E1E1E",
  "Extrudr|FLEX - Black - Medium-ESD": "1E1E1E",
  "Extrudr|FLEX - Black - Semisoft": "1E1E1E",
  "Extrudr|FLEX - Black Hard": "1E1E1E",
  "Extrudr|FLEX - Hellfire Red  - Medium": "F80000",
  "Extrudr|FLEX - Navy Blue - Medium": "1D1E33",
  "Extrudr|FLEX - Neon Green - Medium": "00BB2D",
  "Extrudr|FLEX - Neon Orange - Medium": "FF2301",
  "Extrudr|FLEX - Neon Red - Medium": "F80000",
  "Extrudr|FLEX - Neon Yellow - Medium": "FFFF00",
  "Extrudr|FLEX - Transparent - Medium": "FFFFFF",
  "Extrudr|FLEX - Transparent - Semisoft": "FFFFFF",
  "Extrudr|FLEX - Transparent Hard": "FFFFFF",
  "Extrudr|FLEX - White - Medium": "F4F4F4",
  "Extrudr|FLEX - White - Semisoft": "F4F4F4",
  "Extrudr|FLEX - White Hard": "F4F4F4",
  "Extrudr|Gold": "705335",
  "Extrudr|Grey": "CAC4B0",
  "Extrudr|Hellfire Red ": "F80000",
  "Extrudr|Inca Gold": "F5D033",
  "Extrudr|Jet Black ": "282828",
  "Extrudr|Light Blue": "3B83BD",
  "Extrudr|MATT - Anthracite": "293133",
  "Extrudr|MATT - Black": "1E1E1E",
  "Extrudr|MATT - Blue": "1D1E33",
  "Extrudr|MATT - Military Green": "424632",
  "Extrudr|MATT - Red": "A52019",
  "Extrudr|MATT - Transparent": "FFFFFF",
  "Extrudr|Magenta": "CF3476",
  "Extrudr|Metallic Grey": "828282",
  "Extrudr|Metallic": "828282",
  "Extrudr|Military Green": "424632",
  "Extrudr|NX2-MATT - Anthracite": "293133",
  "Extrudr|NX2-MATT - Black": "1E1E1E",
  "Extrudr|NX2-MATT - Blue Steel": "1E213D",
  "Extrudr|NX2-MATT - Brown": "59351F",
  "Extrudr|NX2-MATT - Emerald Green": "287233",
  "Extrudr|NX2-MATT - Epic Purple": "4A192C",
  "Extrudr|NX2-MATT - Grey": "CAC4B0",
  "Extrudr|NX2-MATT - Hellfire Red ": "F80000",
  "Extrudr|NX2-MATT - Light Blue": "3B83BD",
  "Extrudr|NX2-MATT - Metallic Grey": "828282",
  "Extrudr|NX2-MATT - Military Beige": "C2B078",
  "Extrudr|NX2-MATT - Military Green": "424632",
  "Extrudr|NX2-MATT - Navy Blue": "1D1E33",
  "Extrudr|NX2-MATT - Neon Orange": "FF2301",
  "Extrudr|NX2-MATT - Neon Yellow": "FFFF00",
  "Extrudr|NX2-MATT - Orange": "F54021",
  "Extrudr|NX2-MATT - Purple": "924E7D",
  "Extrudr|NX2-MATT - Signal Green": "008F39",
  "Extrudr|NX2-MATT - Silver": "A5A5A5",
  "Extrudr|NX2-MATT - Turquoise": "3F888F",
  "Extrudr|NX2-MATT - White": "F4F4F4",
  "Extrudr|NX2-MATT - Yellow": "FAD201",
  "Extrudr|Nature": "EAE6CA",
  "Extrudr|Navy Blue": "1D1E33",
  "Extrudr|Neon Green": "00BB2D",
  "Extrudr|Neon Orange": "FF2301",
  "Extrudr|Neon Red": "F80000",
  "Extrudr|Neon Yellow": "FFFF00",
  "Extrudr|Orange": "F54021",
  "Extrudr|Pro Anthracite": "293133",
  "Extrudr|Pro Black ": "1E1E1E",
  "Extrudr|Pro Black": "1E1E1E",
  "Extrudr|Pro Hellfire Red": "F80000",
  "Extrudr|Pro Nature": "EAE6CA",
  "Extrudr|Pro Navy Blue": "1D1E33",
  "Extrudr|Pro Silver": "A5A5A5",
  "Extrudr|Pro White": "F4F4F4",
  "Extrudr|Purple": "924E7D",
  "Extrudr|Quicksilver": "828282",
  "Extrudr|Red": "A52019",
  "Extrudr|Reptile Green": "1C542D",
  "Extrudr|Signal Green": "008F39",
  "Extrudr|Silver": "A5A5A5",
  "Extrudr|Steampunk Copper": "763C28",
  "Extrudr|Transparent Blue": "2A6478",
  "Extrudr|Transparent Green": "57A639",
  "Extrudr|Transparent Orange": "D84B20",
  "Extrudr|Transparent Red": "9B111E",
  "Extrudr|Transparent Yellow": "E5BE01",
  "Extrudr|Transparent": "FFFFFF",
  "Extrudr|Turquoise": "3F888F",
  "Extrudr|Venom Green": "C0DF16",
  "Extrudr|White": "F4F4F4",
  "Extrudr|X - Black REC": "1E1E1E",
  "Extrudr|X - Black": "1E1E1E",
  "Extrudr|X - Transparent REC": "FFFFFF",
  "Extrudr|X - White REC": "F4F4F4",
  "Extrudr|Yellow": "FAD201",
  "Extrudr|glowEx": "00BB2D",
  "Polymaker|Fiberon™ PA12-CF10 Black": "000000",
  "Polymaker|Fiberon™ PA6-CF20 Black": "000000",
  "Polymaker|Fiberon™ PA6-GF25 Grey": "9B9B9B",
  "Polymaker|Panchroma™ (Formerly PolyLite™) Luminous Blue": "419EC2",
  "Polymaker|Panchroma™ (Formerly PolyLite™) Luminous Green": "75DF69",
  "Polymaker|Panchroma™ (Formerly PolyLite™) Luminous Orange": "EC7626",
  "Polymaker|Panchroma™ (Formerly PolyLite™) Luminous Pink": "F48079",
  "Polymaker|Panchroma™ (Formerly PolyLite™) Luminous Yellow": "CCC93C",
  "Polymaker|Panchroma™ Marble (Formerly PolyTerra™ Marble) Brick": "CF6646",
  "Polymaker|Panchroma™ Marble (Formerly PolyTerra™ Marble) Limestone": "BFBFB3",
  "Polymaker|Panchroma™ Marble (Formerly PolyTerra™ Marble) Sandstone": "C6C781",
  "Polymaker|Panchroma™ Marble (Formerly PolyTerra™ Marble) Slate Grey": "91C2CC",
  "Polymaker|Panchroma™ Marble (Formerly PolyTerra™ Marble) White": "CFCCD6",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Arctic Teal": "5AABB1",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Army Beige": "CCA897",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Army Blue": "062B4D",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Army Brown": "724E3D",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Army Dark Green": "515234",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Army Light Green": "A78403",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Army Purple": "292036",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Army Red": "AC1A17",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Ash Grey": "575E75",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Charcoal Black": "1C1C1C",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Cotton White": "E6DDDB",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Earth Brown": "7C594A",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Electric Indigo": "764C99",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Forest Green": "519F61",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Fossil Grey": "6F727E",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Lava Red": "DE1619",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Lavender Purple": "8A68B5",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Lime Green": "D0E740",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Lotus Pink": "F98289",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Muted Blue": "4E6A84",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Muted Green": "656D60",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Muted Purple": "7C5577",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Muted Red": "DB3E14",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Muted White": "AFA198",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Pastel Banana": "F5CF6F",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Pastel Candy": "DABCC8",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Pastel Ice": "95C5D3",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Pastel Mint": "BEC9A5",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Pastel Peach": "F2B67A",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Pastel Peanut": "C29572",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Pastel Periwinkle": "BFB2E6",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Pastel Watermelon": "E93A3F",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Sakura Pink": "E0A8BB",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Sapphire Blue": "005AA2",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Savannah Yellow": "F0BE02",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Sky Blue": "87CEEB",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Sunrise Orange": "F78E0E",
  "Polymaker|Panchroma™ Matte (Formerly PolyTerra™) Wood Brown": "AD7441",
  "Polymaker|Panchroma™ Regular Aqua Blue": "39B9DB",
  "Polymaker|Panchroma™ Regular Azure Blue": "0066D9",
  "Polymaker|Panchroma™ Regular Beige": "C6AD74",
  "Polymaker|Panchroma™ Regular Black": "080A0D",
  "Polymaker|Panchroma™ Regular Blue": "003776",
  "Polymaker|Panchroma™ Regular Brown": "55331A",
  "Polymaker|Panchroma™ Regular Cold White": "EAECF5",
  "Polymaker|Panchroma™ Regular Cream": "E5C8A2",
  "Polymaker|Panchroma™ Regular Dark Blue": "041B3D",
  "Polymaker|Panchroma™ Regular Dark Grey Green": "4C5F46",
  "Polymaker|Panchroma™ Regular Green": "06924D",
  "Polymaker|Panchroma™ Regular Grey": "8C9099",
  "Polymaker|Panchroma™ Regular Jungle Green": "446B20",
  "Polymaker|Panchroma™ Regular Lemon Yellow": "F1D335",
  "Polymaker|Panchroma™ Regular Lime Green": "DEDE00",
  "Polymaker|Panchroma™ Regular Magenta": "F2306E",
  "Polymaker|Panchroma™ Regular Natural": "E8E6D0",
  "Polymaker|Panchroma™ Regular Olive Brown": "A79565",
  "Polymaker|Panchroma™ Regular Olive Green": "857C00",
  "Polymaker|Panchroma™ Regular Orange": "F67405",
  "Polymaker|Panchroma™ Regular Pink": "EE9BB5",
  "Polymaker|Panchroma™ Regular Polymaker Teal": "4CC0C7",
  "Polymaker|Panchroma™ Regular Purple": "6C47B2",
  "Polymaker|Panchroma™ Regular Red": "E72F1D",
  "Polymaker|Panchroma™ Regular Steel Grey": "616469",
  "Polymaker|Panchroma™ Regular Stone Blue": "40719A",
  "Polymaker|Panchroma™ Regular White": "E2DEDB",
  "Polymaker|Panchroma™ Regular Wine Red": "E0191E",
  "Polymaker|Panchroma™ Regular Yellow": "F3B400",
  "Polymaker|PolyCast™ Natural": "E8E6D0",
  "Polymaker|PolyDissolve™ S1 (PVA) Natural": "E8E6D0",
  "Polymaker|PolyFlex™ TPU90 Black": "101820",
  "Polymaker|PolyFlex™ TPU90 Clear": "F4FAFC",
  "Polymaker|PolyFlex™ TPU90 Grey": "453536",
  "Polymaker|PolyFlex™ TPU90 Polymaker Teal": "2DCCD3",
  "Polymaker|PolyFlex™ TPU90 White": "FFFFFF",
  "Polymaker|PolyFlex™ TPU95 Black": "101820",
  "Polymaker|PolyFlex™ TPU95 Blue": "0076CF",
  "Polymaker|PolyFlex™ TPU95 Orange": "FF9E1B",
  "Polymaker|PolyFlex™ TPU95 Red": "D6001C",
  "Polymaker|PolyFlex™ TPU95 White": "FFFFFF",
  "Polymaker|PolyFlex™ TPU95 Yellow": "FEDD00",
  "Polymaker|PolyFlex™ TPU95-HF Black": "101820",
  "Polymaker|PolyFlex™ TPU95-HF Clear": "F4FAFC",
  "Polymaker|PolyFlex™ TPU95-HF White": "FFFFFF",
  "Polymaker|PolyLite CosPLA Version A": "B1B1B1",
  "Polymaker|PolyLite CosPLA Version B": "B1B1B1",
  "Polymaker|PolyLite™ ASA Army Brown": "775C50",
  "Polymaker|PolyLite™ ASA Army Green": "68724D",
  "Polymaker|PolyLite™ ASA Black": "101820",
  "Polymaker|PolyLite™ ASA Blue": "002677",
  "Polymaker|PolyLite™ ASA Dark Green Grey": "4C5F46",
  "Polymaker|PolyLite™ ASA Dark Grey": "6C6D71",
  "Polymaker|PolyLite™ ASA Dark Purple": "292036",
  "Polymaker|PolyLite™ ASA Green": "00A95C",
  "Polymaker|PolyLite™ ASA Grey": "888B8D",
  "Polymaker|PolyLite™ ASA Jet Black": "0A0A0A",
  "Polymaker|PolyLite™ ASA Natural": "F1E6B2",
  "Polymaker|PolyLite™ ASA Olive Brown": "A79565",
  "Polymaker|PolyLite™ ASA Orange": "FF6A13",
  "Polymaker|PolyLite™ ASA Polymaker Teal": "00B4BC",
  "Polymaker|PolyLite™ ASA Pop Blue": "2A9BEE",
  "Polymaker|PolyLite™ ASA Pop Green": "3CEE2A",
  "Polymaker|PolyLite™ ASA Pop Pink": "EA4E8E",
  "Polymaker|PolyLite™ ASA Purple": "7758B3",
  "Polymaker|PolyLite™ ASA Red": "AF231C",
  "Polymaker|PolyLite™ ASA White": "FFFFFF",
  "Polymaker|PolyLite™ ASA Yellow": "FFE800",
  "Polymaker|PolyLite™ PC Clear": "F4FAFC",
  "Polymaker|PolyLite™ PETG Black": "101820",
  "Polymaker|PolyLite™ PETG Blue": "004B87",
  "Polymaker|PolyLite™ PETG Clear": "F4FAFC",
  "Polymaker|PolyLite™ PETG Dark Blue": "13294B",
  "Polymaker|PolyLite™ PETG Dark Green": "3D441E",
  "Polymaker|PolyLite™ PETG Dark Grey": "6C6D71",
  "Polymaker|PolyLite™ PETG Dark Purple": "292036",
  "Polymaker|PolyLite™ PETG Electric Blue": "0076CF",
  "Polymaker|PolyLite™ PETG Gold": "CC8A00",
  "Polymaker|PolyLite™ PETG Green": "37AD68",
  "Polymaker|PolyLite™ PETG Grey": "91999F",
  "Polymaker|PolyLite™ PETG Lime": "C4D600",
  "Polymaker|PolyLite™ PETG Magenta": "C6007E",
  "Polymaker|PolyLite™ PETG Orange": "FF671F",
  "Polymaker|PolyLite™ PETG Pink": "F59BBB",
  "Polymaker|PolyLite™ PETG Polymaker Teal": "2DCCD3",
  "Polymaker|PolyLite™ PETG Purple": "6E3FA3",
  "Polymaker|PolyLite™ PETG Red": "DE4343",
  "Polymaker|PolyLite™ PETG Silver": "75787B",
  "Polymaker|PolyLite™ PETG White": "FFFFFF",
  "Polymaker|PolyLite™ PETG Yellow": "FFC845",
  "Polymaker|PolyLite™ PLA Aqua Blue": "39B9DB",
  "Polymaker|PolyLite™ PLA Azure Blue": "0066D9",
  "Polymaker|PolyLite™ PLA Beige": "C6AD74",
  "Polymaker|PolyLite™ PLA Black": "08090D",
  "Polymaker|PolyLite™ PLA Blue": "003776",
  "Polymaker|PolyLite™ PLA Brown": "55331A",
  "Polymaker|PolyLite™ PLA Cream": "E5C8A2",
  "Polymaker|PolyLite™ PLA Dark Blue": "041B3D",
  "Polymaker|PolyLite™ PLA Green": "06924D",
  "Polymaker|PolyLite™ PLA Grey": "8C9099",
  "Polymaker|PolyLite™ PLA Jungle Green": "446B20",
  "Polymaker|PolyLite™ PLA Lemon Yellow": "F1D335",
  "Polymaker|PolyLite™ PLA Lime Green": "DEDE00",
  "Polymaker|PolyLite™ PLA Magenta": "F2306E",
  "Polymaker|PolyLite™ PLA Natural": "E8E6D0",
  "Polymaker|PolyLite™ PLA Olive Green": "857C00",
  "Polymaker|PolyLite™ PLA Orange": "F67405",
  "Polymaker|PolyLite™ PLA Pink": "F2306E",
  "Polymaker|PolyLite™ PLA Polymaker Teal": "4CC0C7",
  "Polymaker|PolyLite™ PLA Pro Army Beige": "AA6F3E",
  "Polymaker|PolyLite™ PLA Pro Army Green": "665A28",
  "Polymaker|PolyLite™ PLA Pro Black": "0C0E0C",
  "Polymaker|PolyLite™ PLA Pro Blue": "00307E",
  "Polymaker|PolyLite™ PLA Pro Blue-Green": "00272F",
  "Polymaker|PolyLite™ PLA Pro Brown": "4F2E1E",
  "Polymaker|PolyLite™ PLA Pro Cold White": "EAECF5",
  "Polymaker|PolyLite™ PLA Pro Dark Purple": "292036",
  "Polymaker|PolyLite™ PLA Pro Dark2 Grey": "6C6D71",
  "Polymaker|PolyLite™ PLA Pro Green": "178D4A",
  "Polymaker|PolyLite™ PLA Pro Grey": "73767D",
  "Polymaker|PolyLite™ PLA Pro Light Blue": "72AECB",
  "Polymaker|PolyLite™ PLA Pro Light Green": "BBD39B",
  "Polymaker|PolyLite™ PLA Pro Light Red": "CC4C4B",
  "Polymaker|PolyLite™ PLA Pro Light Yellow": "F3D561",
  "Polymaker|PolyLite™ PLA Pro Magenta": "E42363",
  "Polymaker|PolyLite™ PLA Pro Orange": "EC6A01",
  "Polymaker|PolyLite™ PLA Pro Pink": "ED92B0",
  "Polymaker|PolyLite™ PLA Pro Polymaker Teal": "2FA5AE",
  "Polymaker|PolyLite™ PLA Pro Purple": "6843B1",
  "Polymaker|PolyLite™ PLA Pro Red": "E62216",
  "Polymaker|PolyLite™ PLA Pro White": "E6E1DE",
  "Polymaker|PolyLite™ PLA Pro Yellow": "F7B300",
  "Polymaker|PolyLite™ PLA Purple": "6C47B2",
  "Polymaker|PolyLite™ PLA Red": "E72F1D",
  "Polymaker|PolyLite™ PLA Steel Grey": "616469",
  "Polymaker|PolyLite™ PLA Stone Blue": "40719A",
  "Polymaker|PolyLite™ PLA White": "E2DEDB",
  "Polymaker|PolyLite™ PLA Wine Red": "E0191E",
  "Polymaker|PolyLite™ PLA Yellow": "F3B400",
  "Polymaker|PolyLite™ ABS Black": "16161A",
  "Polymaker|PolyLite™ ABS Blue": "003276",
  "Polymaker|PolyLite™ ABS Dark Grey": "474648",
  "Polymaker|PolyLite™ ABS Dark Purple": "292036",
  "Polymaker|PolyLite™ ABS Galaxy Black": "474648",
  "Polymaker|PolyLite™ ABS Galaxy Dark Grey": "474648",
  "Polymaker|PolyLite™ ABS Galaxy Orange": "F57517",
  "Polymaker|PolyLite™ ABS Galaxy Purple": "6545A5",
  "Polymaker|PolyLite™ ABS Galaxy Teal": "2DCCD3",
  "Polymaker|PolyLite™ ABS Gold": "BD6200",
  "Polymaker|PolyLite™ ABS Green": "479161",
  "Polymaker|PolyLite™ ABS Grey": "8C8D93",
  "Polymaker|PolyLite™ ABS Light Blue": "8EDBEB",
  "Polymaker|PolyLite™ ABS Lime": "C4D100",
  "Polymaker|PolyLite™ ABS Metallic Blue": "043371",
  "Polymaker|PolyLite™ ABS Metallic Green": "3D441E",
  "Polymaker|PolyLite™ ABS Natural": "E2E0C9",
  "Polymaker|PolyLite™ ABS Neon Green": "77F0A2",
  "Polymaker|PolyLite™ ABS Neon Magenta": "F6162E",
  "Polymaker|PolyLite™ ABS Neon Orange": "FE602B",
  "Polymaker|PolyLite™ ABS Neon Yellow": "FFC001",
  "Polymaker|PolyLite™ ABS Orange": "F57517",
  "Polymaker|PolyLite™ ABS Pink": "FFA7C4",
  "Polymaker|PolyLite™ ABS Purple": "6545A5",
  "Polymaker|PolyLite™ ABS Red": "F3442B",
  "Polymaker|PolyLite™ ABS Teal": "01ACBA",
  "Polymaker|PolyLite™ ABS White": "F0EBE8",
  "Polymaker|PolyLite™ ABS Yellow": "EDA900",
  "Polymaker|PolyLite™ LW-PLA Black": "4C4E56",
  "Polymaker|PolyLite™ LW-PLA Bright Green": "D0ED03",
  "Polymaker|PolyLite™ LW-PLA Bright Orange": "FA8423",
  "Polymaker|PolyLite™ LW-PLA Bright Red": "E81313",
  "Polymaker|PolyLite™ LW-PLA Bright Yellow": "FAD61B",
  "Polymaker|PolyLite™ LW-PLA Grey": "A2AAAD",
  "Polymaker|PolyLite™ LW-PLA White": "E1DCCD",
  "Polymaker|PolyLite™ LW-PLA Wood": "D2A273",
  "Polymaker|PolyMax™ PC Black": "101820",
  "Polymaker|PolyMax™ PC Blue": "0076CF",
  "Polymaker|PolyMax™ PC Grey": "A2AAAD",
  "Polymaker|PolyMax™ PC Red": "D6001C",
  "Polymaker|PolyMax™ PC White": "FFFFFF",
  "Polymaker|PolyMax™ PLA Black": "101820",
  "Polymaker|PolyMax™ PLA Blue": "006EB6",
  "Polymaker|PolyMax™ PLA FDE": "8E7B63",
  "Polymaker|PolyMax™ PLA Green": "00A95C",
  "Polymaker|PolyMax™ PLA Grey": "91999F",
  "Polymaker|PolyMax™ PLA Orange": "FF9940",
  "Polymaker|PolyMax™ PLA Pink": "FD4BAB",
  "Polymaker|PolyMax™ PLA Polymaker Teal": "00B4BC",
  "Polymaker|PolyMax™ PLA Purple": "7758B3",
  "Polymaker|PolyMax™ PLA Red": "DE4343",
  "Polymaker|PolyMax™ PLA White": "FFFFFF",
  "Polymaker|PolyMax™ PLA Yellow": "FFE800",
  "Polymaker|PolyMax™ PC-FR Black": "101820",
  "Polymaker|PolyMax™ PC-FR White": "FFFFFF",
  "Polymaker|PolyMax™ PETG Black": "101820",
  "Polymaker|PolyMax™ PETG White": "FFFFFF",
  "Polymaker|PolyMide™ CoPA Black": "101820",
  "Polymaker|PolySmooth™ Beige": "E9DF97",
  "Polymaker|PolySmooth™ Black": "101820",
  "Polymaker|PolySmooth™ Blue": "0076CF",
  "Polymaker|PolySmooth™ Clear": "F4FAFC",
  "Polymaker|PolySmooth™ Coral Red": "E10600",
  "Polymaker|PolySmooth™ Green": "37AD68",
  "Polymaker|PolySmooth™ Orange": "FF671F",
  "Polymaker|PolySmooth™ Pink": "FFB1BB",
  "Polymaker|PolySmooth™ Polymaker Teal": "3CCBDA",
  "Polymaker|PolySmooth™ Slate Grey": "7A99AC",
  "Polymaker|PolySmooth™ White": "FFFFFF",
  "Polymaker|PolySmooth™ Yellow": "FFC72C",
  "Polymaker|PolySonic™ PLA Black": "080A0D",
  "Polymaker|PolySonic™ PLA Blue": "003776",
  "Polymaker|PolySonic™ PLA Green": "2D9E59",
  "Polymaker|PolySonic™ PLA Grey": "8C9099",
  "Polymaker|PolySonic™ PLA Orange": "F97429",
  "Polymaker|PolySonic™ PLA Polymaker Teal": "50DAE4",
  "Polymaker|PolySonic™ PLA Pro Black": "080A0D",
  "Polymaker|PolySonic™ PLA Pro Blue": "003287",
  "Polymaker|PolySonic™ PLA Pro Green": "2D9E59",
  "Polymaker|PolySonic™ PLA Pro Grey": "959FA1",
  "Polymaker|PolySonic™ PLA Pro Orange": "F97429",
  "Polymaker|PolySonic™ PLA Pro Polymaker Teal": "50DAE4",
  "Polymaker|PolySonic™ PLA Pro Purple": "6C5BB1",
  "Polymaker|PolySonic™ PLA Pro Red": "E20010",
  "Polymaker|PolySonic™ PLA Pro White": "E2DEDB",
  "Polymaker|PolySonic™ PLA Pro Yellow": "F4C032",
  "Polymaker|PolySonic™ PLA Purple": "6C5BB1",
  "Polymaker|PolySonic™ PLA Red": "E72F1D",
  "Polymaker|PolySonic™ PLA White": "E2DEDB",
  "Polymaker|PolySonic™ PLA Yellow": "F4C032",
  "Polymaker|PolyWood™ Wood": "D2A273",
  "Polymaker|Polymaker PC-ABS Black": "101820",
  "Polymaker|Polymaker PC-ABS White": "FFFFFF",
  "Polymaker|Polymaker PC-PBT Black": "101820",
  "Polymaker|Polymaker PC-PBT Natural": "E8E6D0",
  "eSun|Black": "111214",
  "eSun|Blue": "153A66",
  "eSun|Brown": "5B4337",
  "eSun|Change by temp": "D93325",
  "eSun|Cold White": "DBDBDD",
  "eSun|Fire Engine Red": "952428",
  "eSun|Green": "00AB84",
  "eSun|Grey": "615F6C",
  "eSun|Light Blue": "0097B7",
  "eSun|Magenta": "C1484F",
  "eSun|Natural": "BEB8AC",
  "eSun|Orange": "E89746",
  "eSun|PLA Wood": "EBCFA7",
  "eSun|PLA+ ALMOND YELLOW": "DFD590",
  "eSun|PLA+ APRICOT": "E68A1D",
  "eSun|PLA+ BABY BLUE": "75C2CA",
  "eSun|PLA+ BABY PINK": "CD8E89",
  "eSun|PLA+ Beige": "EABCA2",
  "eSun|PLA+ Black": "000000",
  "eSun|PLA+ Blue": "1932B3",
  "eSun|PLA+ Bone White": "E0D7B6",
  "eSun|PLA+ Brown": "935931",
  "eSun|PLA+ CORAL ORANGE": "FF7E23",
  "eSun|PLA+ Cold White": "E2F6F7",
  "eSun|PLA+ Dark Blue": "232845",
  "eSun|PLA+ Fire Engine Red": "952426",
  "eSun|PLA+ Gold": "F2B01C",
  "eSun|PLA+ Grass Green": "049840",
  "eSun|PLA+ Green": "00101A",
  "eSun|PLA+ Grey": "606783",
  "eSun|PLA+ Haze Blue": "468DB9",
  "eSun|PLA+ Holly Green": "014D41",
  "eSun|PLA+ Jade Green": "02C5A7",
  "eSun|PLA+ LIGHT KHAKI": "BDB7A1",
  "eSun|PLA+ LILAC": "C78DBF",
  "eSun|PLA+ Light Blue": "169BEA",
  "eSun|PLA+ Light Brown": "9E744A",
  "eSun|PLA+ MATCHA GREEN": "91994C",
  "eSun|PLA+ MILKY WHITE": "D6D5D0",
  "eSun|PLA+ MINT GREEN": "69C296",
  "eSun|PLA+ Magenta": "E02552",
  "eSun|PLA+ Mustard Green": "DEDF93",
  "eSun|PLA+ Olive Green": "455C40",
  "eSun|PLA+ Orange": "E47B20",
  "eSun|PLA+ PEACH PINK": "DAB4B1",
  "eSun|PLA+ Peak Green": "46CA43",
  "eSun|PLA+ Pine Green": "063C22",
  "eSun|PLA+ Pink": "EF7AA4",
  "eSun|PLA+ Purple": "793EB6",
  "eSun|PLA+ RGB BLUE": "303ED2",
  "eSun|PLA+ RGB GREEN": "0CB234",
  "eSun|PLA+ RGB RED": "E62409",
  "eSun|PLA+ Red": "DC4638",
  "eSun|PLA+ Silver": "9B9AA2",
  "eSun|PLA+ Sky Blue": "7CD1F6",
  "eSun|PLA+ Space Blue": "33AAEE",
  "eSun|PLA+ Very peri": "8683EA",
  "eSun|PLA+ White": "FFFFFF",
  "eSun|PLA+ Yellow": "D9AA26",
  "eSun|PLA-Basic Aqua": "42C3D7",
  "eSun|PLA-Basic Barbie Pink": "FD838E",
  "eSun|PLA-Basic Beige": "E1AC8C",
  "eSun|PLA-Basic Black": "0F0F0F",
  "eSun|PLA-Basic Blue": "1533C5",
  "eSun|PLA-Basic Bone White": "DCC7B2",
  "eSun|PLA-Basic Brown": "634432",
  "eSun|PLA-Basic Cold White": "DBEEFD",
  "eSun|PLA-Basic Concrete Grey": "B3B3B3",
  "eSun|PLA-Basic Dark Blue": "3A4056",
  "eSun|PLA-Basic Fire Engine Red": "8D091E",
  "eSun|PLA-Basic Grape Purple": "6E2D91",
  "eSun|PLA-Basic Green": "068E1F",
  "eSun|PLA-Basic Grey": "536782",
  "eSun|PLA-Basic Holly Green": "3F8278",
  "eSun|PLA-Basic Light Blue": "4D9CE1",
  "eSun|PLA-Basic Light Grey": "536C8B",
  "eSun|PLA-Basic Olive Green": "535645",
  "eSun|PLA-Basic Orange": "FDA42E",
  "eSun|PLA-Basic Peak Green": "A9D47B",
  "eSun|PLA-Basic Pink": "FF6762",
  "eSun|PLA-Basic Purple": "A60056",
  "eSun|PLA-Basic Red": "D54837",
  "eSun|PLA-Basic Silver": "888D93",
  "eSun|PLA-Basic Sky Blue": "63D0F9",
  "eSun|PLA-Basic White": "FFFFFF",
  "eSun|PLA-Basic Yellow": "F8DF20",
  "eSun|PLA-Luminous Cored Luminous Blue": "2C95CC",
  "eSun|PLA-Luminous Cored Luminous Green": "3C4242",
  "eSun|PLA-Luminous Cored Luminous Orange": "FF977F",
  "eSun|PLA-Luminous Cored Luminous Purple": "997ABD",
  "eSun|PLA-Luminous Luminous Blue": "2C95CC",
  "eSun|PLA-Luminous Luminous Green": "3C4242",
  "eSun|PLA-Matte ALMOND YELLOW": "DDECB3",
  "eSun|PLA-Matte BLACK": "272928",
  "eSun|PLA-Matte DARK GREY": "596484",
  "eSun|PLA-Matte LIGHT BLUE": "85BACA",
  "eSun|PLA-Matte LIGHT KHAKI": "C7B8A5",
  "eSun|PLA-Matte LILAC": "E1BAE6",
  "eSun|PLA-Matte MATCHA GREEN": "90BA66",
  "eSun|PLA-Matte MILKY WHITE": "DFDBD8",
  "eSun|PLA-Matte MINT GREEN": "8DBDA3",
  "eSun|PLA-Matte MORANDI GREEN": "0D353D",
  "eSun|PLA-Matte MORANDI PURPLE": "90BA66",
  "eSun|PLA-Matte PEACH PINK": "F4B1C2",
  "eSun|PLA-Matte Rainbow": "D1D8AE",
  "eSun|PLA-Matte STRAWBERRY RED": "F88BA2",
  "eSun|PLA-Matte TANGERINE": "FF7537",
  "eSun|PLA-Silk Magic Black Gold": "AB5B26",
  "eSun|PLA-Silk Magic Black Green": "5D9288",
  "eSun|PLA-Silk Magic Black Purple": "583A60",
  "eSun|PLA-Silk Magic Black Red": "A82C2C",
  "eSun|PLA-Silk Magic Blue Green": "02254B",
  "eSun|PLA-Silk Magic Gold Silver": "FDCF91",
  "eSun|PLA-Silk Magic Purple Gold": "C592A5",
  "eSun|PLA-Silk Magic Red Blue": "0061AF",
  "eSun|PLA-Silk Magic Red Gold": "EE3137",
  "eSun|PLA-Silk Magic Red Green": "0A4C1E",
  "eSun|PLA-Silk Magic Silver Blue": "0E2F8E",
  "eSun|PLA-Silk Mystic BLUE ORANGE GREEN": "F7B585",
  "eSun|PLA-Silk Mystic BLUE RED PURPLE": "5C0242",
  "eSun|PLA-Silk Mystic COPPER PURPLE GREEN": "7C5F95",
  "eSun|PLA-Silk Mystic GOLD BLUE PURPLE": "3F409A",
  "eSun|PLA-Silk Mystic GOLD GREEN BLACK": "534737",
  "eSun|PLA-Silk Mystic GOLD GREEN PURPLE": "C58A0C",
  "eSun|PLA-Silk Mystic GOLD RED GREEN": "B5334D",
  "eSun|PLA-Silk Mystic GOLD SILVER COPPER": "BDBAB1",
  "eSun|PLA-Silk Mystic RED BLACK GOLD": "2A2426",
  "eSun|PLA-Silk Mystic RED GOLD PURPLE": "FD9E0C",
  "eSun|PLA-Silk Mystic RED GREEN BLUE": "223265",
  "eSun|PLA-Silk Mystic RED YELLOW BLUE": "ECE280",
  "eSun|PLA-lite BLACK": "101211",
  "eSun|PLA-lite BLUE": "0D2C7C",
  "eSun|PLA-lite COLD WHITE": "FFFFFF",
  "eSun|PLA-lite FIRE ENGINE RED": "8B282D",
  "eSun|PLA-lite GREEN": "3E484A",
  "eSun|PLA-lite GREY": "1A3059",
  "eSun|PLA-lite ORANGE": "FC6401",
  "eSun|PLA-lite VERY PERI": "675DF1",
  "eSun|PLA-lite WHITE": "C2C1BD",
  "eSun|PLA-lite YELLOW": "F6DC01",
  "eSun|Peak Green": "4DA036",
  "eSun|Pine Green": "244435",
  "eSun|Pink": "EB586A",
  "eSun|Purple": "3E1750",
  "eSun|Rainbow": "889874",
  "eSun|Red": "D12A31",
  "eSun|Silver": "797876",
  "eSun|Solid Black": "070707",
  "eSun|Solid Blue": "0F1D5C",
  "eSun|Solid Gold": "E0A000",
  "eSun|Solid Green": "015A44",
  "eSun|Solid Grey": "435A83",
  "eSun|Solid Orange": "FF6924",
  "eSun|Solid Purple": "865D97",
  "eSun|Solid Red": "D82A33",
  "eSun|Solid Silver": "878286",
  "eSun|Solid White": "D4CAD2",
  "eSun|Solid Yellow": "E0A000",
  "eSun|Tansparent Blue": "108EDB",
  "eSun|Transparent Green": "02B31A",
  "eSun|Transparent Orange": "FF8126",
  "eSun|Transparent Pink": "D53857",
  "eSun|Transparent Purple": "851D4E",
  "eSun|Transparent Red": "982A2B",
  "eSun|Transparent Yellow": "E5E002",
  "eSun|White": "FFFFFF",
  "eSun|Yellow": "EAE412",
  "eSun|ePLA+HS Beige": "E8B99F",
  "eSun|ePLA+HS Black": "000000",
  "eSun|ePLA+HS Blue": "12296F",
  "eSun|ePLA+HS Bone White": "A88567",
  "eSun|ePLA+HS Brown": "6A4A3D",
  "eSun|ePLA+HS Cold White": "EFEEF3",
  "eSun|ePLA+HS Dark Blue": "1D2333",
  "eSun|ePLA+HS Fire Engine Red": "A40F15",
  "eSun|ePLA+HS Gold": "E39D3E",
  "eSun|ePLA+HS Green": "4B585E",
  "eSun|ePLA+HS Grey": "A6A9AE",
  "eSun|ePLA+HS Light Blue": "29B9DE",
  "eSun|ePLA+HS Light Brown": "B47F5F",
  "eSun|ePLA+HS Magenta": "ED5973",
  "eSun|ePLA+HS Olive Green": "6D6B5E",
  "eSun|ePLA+HS Orange": "FF5216",
  "eSun|ePLA+HS Peak Green": "7AC163",
  "eSun|ePLA+HS Pine Green": "43634E",
  "eSun|ePLA+HS Pink": "FF7083",
  "eSun|ePLA+HS Purple": "3B1D4F",
  "eSun|ePLA+HS Red": "FE4A3B",
  "eSun|ePLA+HS Silver": "757376",
  "eSun|ePLA+HS Space Blue": "5CB5DF",
  "eSun|ePLA+HS Very Peri": "867EC9",
  "eSun|ePLA+HS White": "FFFFFF",
  "eSun|ePLA+HS Yellow": "FAD900",
  "eSun|ePLA-Silk Blue": "0064EE",
  "eSun|ePLA-Silk Bronze": "5B5F50",
  "eSun|ePLA-Silk Copper": "EE771B",
  "eSun|ePLA-Silk Cyan": "0A75C3",
  "eSun|ePLA-Silk Dark Yellow": "FBB351",
  "eSun|ePLA-Silk Gold": "E89104",
  "eSun|ePLA-Silk Green": "00CD20",
  "eSun|ePLA-Silk Jacinth": "EE422A",
  "eSun|ePLA-Silk Lime": "A7E51E",
  "eSun|ePLA-Silk Pink": "FF8FCA",
  "eSun|ePLA-Silk Purple": "6D22A3",
  "eSun|ePLA-Silk Red": "FF2C30",
  "eSun|ePLA-Silk Rose Gold": "ED5973",
  "eSun|ePLA-Silk Silver": "B1B1B3",
  "eSun|ePLA-Silk Violet": "FB78BC",
  "eSun|ePLA-Silk White": "FFFFFF",
  "eSun|ePLA-Silk Yellow": "E1BE1A",
};
